//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemiShitjesPOS.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemiShitjesPOS.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1024x768_data_uploads_19_347979_scary_forest_dark_pictures {
            get {
                object obj = ResourceManager.GetObject("1024x768-data-uploads-19-347979-scary-forest-dark-pictures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cover1 {
            get {
                object obj = ResourceManager.GetObject("cover1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_address_card_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_address-card_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_close_50_0_696969_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_close_50_0_696969_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_euro_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_euro_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_burst_sale_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_burst-sale_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_burst_sale_80_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_burst-sale_80_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_clipboard_notes_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_clipboard-notes_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_shopping_bag_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_shopping-bag_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_menu_25_25_a7bccd_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_menu_25_25_a7bccd_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_price_tags_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_price-tags_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_stats_bars_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_stats-bars_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_truck_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_truck_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_close_25_0_696969_none {
            get {
                object obj = ResourceManager.GetObject("ionicons_2-0-1_close_25_0_696969_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_close_25_25_696969_none {
            get {
                object obj = ResourceManager.GetObject("ionicons_2-0-1_close_25_25_696969_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_ios_people_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("ionicons_2-0-1_ios-people_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ligature_symbols_2_11_0_human_25_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("ligature-symbols_2-11-0_human_25_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ligature_symbols_2_11_0_logout_30_0_647d91_none {
            get {
                object obj = ResourceManager.GetObject("ligature-symbols_2-11-0_logout_30_0_647d91_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ligature_symbols_2_11_0_logout_30_0_ff0000_none {
            get {
                object obj = ResourceManager.GetObject("ligature-symbols_2-11-0_logout_30_0_ff0000_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_icons_3_0_1_dashboard_100_0_506c82_none {
            get {
                object obj = ResourceManager.GetObject("material-icons_3-0-1_dashboard_100_0_506c82_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
